name: "Run Stryker"
author: "Tom van den Berg"
description: "Github action to run Stryker to validate your tests 👽👾"
branding:
  icon: 'zap'
  color: 'red'
inputs:
  tool:
    description: "The type of stryker that you want to run (accepted values: Stryker.NET)"
    required: true
  testProject:
    description: "The path to the test project directory (e.g. BusinessLogic.Test/)"
    required: true
  breakAt:
    description: "When threshold break is set to anything other than 0 and the mutation score is lower than the threshold Stryker will exit with a non-zero code."
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Check strykerVersion
      if: ${{ inputs.strykerVersion != 'Stryker.NET' }}
      run: |
        echo "Invalid strykerVersion. Expected 'Stryker.NET'."
        exit 1
      shell: bash 

    - name: Run Stryker.NET
      if: ${{ inputs.strykerVersion == 'Stryker.NET' }}
      shell: bash
      run: | 
        docker run \
          -v ${{ github.workspace }}:/workspace \
          ghcr.io/stryker-mutator/run-stryker-net:11-support-strykerjs-to-be-ran-with-this-action \
          /workspace/${{ inputs.testProject }} \
          ${{ inputs.breakAt }}  \
          
