name: "Run Stryker.NET"
author: "Tom van den Berg"
description: "Github action to run Stryker.NET"
branding:
  icon: 'zap'
  color: 'green'
inputs:
  testProject:
    description: "The path to the test project directory (e.g. BusinessLogic.Test/)"
    required: true
  breakAt:
    description: "When threshold break is set to anything other than 0 and the mutation score is lower than the threshold Stryker will exit with a non-zero code."
    required: false
    default: "0"

runs:
  using: 'docker'
  image: 'run-stryker-net.dockerfile'
  args:
    - ${{ inputs.testProject }}
    - ${{ inputs.breakAt }}
