name: "Run Stryker"
author: "Tom van den Berg"
description: "Github action to run Stryker to validate your tests 👽👾"
branding:
  icon: 'zap'
  color: 'red'
inputs:
  strykerVersion:
    description: "The version of Stryker to use (e.g. Stryker.NET)"
    required: true
  testProject:
    description: "The path to the test project directory (e.g. BusinessLogic.Test/)"
    required: true
  breakAt:
    description: "When threshold break is set to anything other than 0 and the mutation score is lower than the threshold Stryker will exit with a non-zero code."
    required: false
    default: "0"

runs:
  using: 'docker'
  image: 'run-stryker-net.dockerfile --build-arg STRYKER_VERSION=${{ inputs.strykerVersion }}'
  args:
    - ${{ inputs.testProject }}
    - ${{ inputs.breakAt }}
