name: "Run Stryker"
author: "Tom van den Berg"
description: "Github action to run Stryker to validate your tests 👽👾"
branding:
  icon: 'zap'
  color: 'red'
inputs:
  testProject:
    description: "The path to the test project directory (e.g. BusinessLogic.Test/)"
    required: true
  breakAt:
    description: "When threshold break is set to anything other than 0 and the mutation score is lower than the threshold Stryker will exit with a non-zero code."
    required: false
    default: "0"

runs:
  using: 'composite'
  steps:
    - run: docker run run-stryker-net.dockerfile ${{ inputs.testProject }} ${{ inputs.breakAt }}
      shell: bash
